### ISSUE TITLE
404 Error after sending

### ISSUE THREAD

**Issue by euphemos** [evemail/evemail#1]
After sending an error, http://evemail.space/dashboard/fetch is opened, and displays as below. Also note that returning to the site a second time gave the same after logging in.

array:6 [▼
  0 => 145134841
  1 => 145164722
  2 => 145170456
  3 => 145193823
  4 => 145194900
  5 => 145196498
]
Curl {#407 ▼
  +curl: curl resource @13 ▶}
  +id: "58acb9aedd3430.23788507"
  +error: true
  +errorCode: 404
  +errorMessage: "HTTP/1.1 404 Not Found"
  +curlError: false
  +curlErrorCode: 0
  +curlErrorMessage: ""
  +httpError: true
  +httpStatusCode: 404
  +httpErrorMessage: "HTTP/1.1 404 Not Found"
  +baseUrl: "https://esi.tech.ccp.is/v2/universe/names/"
  +url: "https://esi.tech.ccp.is/v2/universe/names/"
  +requestHeaders: CaseInsensitiveArray {#411 ▶}
  +responseHeaders: CaseInsensitiveArray {#412 ▶}
  +rawResponseHeaders: """
    HTTP/1.1 404 Not Found\r\n
    Server: nginx\r\n
    Date: Tue, 21 Feb 2017 22:05:35 GMT\r\n
    Content-Type: application/json\r\n
    Content-Length: 31\r\n
    Access-Control-Allow-Credentials: true\r\n
    Access-Control-Allow-Headers: Content-Type,Authorization,X-User-Agent\r\n
    Access-Control-Allow-Methods: GET,POST,DELETE,PUT,PATCH,OPTIONS\r\n
    Access-Control-Allow-Origin: *\r\n
    Access-Control-Expose-Headers: Content-Type,Warning\r\n
    Access-Control-Max-Age: 600\r\n
    Vary: Accept-Encoding\r\n
    Strict-Transport-Security: max-age=31536000\r\n
    Via: 1.1 google\r\n
    Alt-Svc: clear\r\n
    \r\n
    """
  +responseCookies: []
  +response: {#413 ▶}
  +rawResponse: "{"error": "no valid IDs found"}"
  +beforeSendFunction: null
  +downloadCompleteFunction: null
  +successFunction: null
  +errorFunction: null
  +completeFunction: null
  +fileHandle: null
  -cookies: []
  -headers: CaseInsensitiveArray {#410 ▶}
  -options: array:9 [▶]
  -jsonDecoder: Closure {#408 ▶}
  -jsonPattern: "/^(?:application|text)\/(?:[a-z]+(?:[\.-][0-9a-z]+){0,}[\+\.]|x-)?json(?:-[a-z]+)?/i"
  -xmlDecoder: Closure {#409 ▶}
  -xmlPattern: "~^(?:text/|application/(?:atom\+|rss\+)?)xml~i"
  -defaultDecoder: null
}

**Comment by ddavaham** [comment]
I forgot to remove that. Whoops. Thanks for posting this, but there is an actually bug here that i am hunting.
