### ISSUE TITLE
Default "My Mail" to Inbox, not All Mails

### ISSUE THREAD

**Issue by bahrmichael** [evemail/evemail#13]
I find the app a bit inconvenient, as it doesn't behave like other mail clients. I am generally not interested in what I sent, but what I received.

**Comment by ddavaham** [comment]
The enhancement has been implemented in the fashion of a preference that can set via the preferences window under my settings. The setting only affect logins from the homepage. Clicking on a link on the website that directs back to the dashboard with hit the all filter instead of the label filter.
